version: '3.0'
services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
     - "443:443"
    links:
     - frontend
     - backend
    volumes:
      - ./proxy/config/nginx.conf/:/etc/nginx/nginx.conf/:ro
      - ./proxy/ssl/:/etc/nginx/ssl/:ro
  frontend:
    build: ./frontend
    restart: always
  backend:
    build: ./backend
    restart: always
  